---
apiVersion: v1
kind: Service
metadata:
  name: my-release-name-helm-create
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: helm-create
    app.kubernetes.io/instance: my-release-name

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-name-helm-create
  labels:
    app.kubernetes.io/name: helm-create
    app.kubernetes.io/instance: my-release-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-create
      app.kubernetes.io/instance: my-release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helm-create
        app.kubernetes.io/instance: my-release-name
    spec:
      containers:
        - name: helm-create
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
---

