apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kustomize edit add configmap conf --from-file=conf/sample.conf.toml
configMapGenerator:
- files:
  - conf/sample.conf.toml
  # behavior: merge
  name: conf

# kustomize edit add secret very-secret --from-file=tls/*
secretGenerator:
- files:
  - tls/tls.crt
  - tls/tls.key
  name: very-secret
  type: Opaque
